image: python:3.11.9-slim-bookworm

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y gcc
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install pytest
    - pip install -r requirements.txt  
  script:
    - pytest

variables:
    IMAGE_NAME: rodrigocoutrufo/api-nba
    IMAGE_TAG: python-app-1.0


build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
      DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script: 
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@165.232.65.184 "
           docker login -u $REGISTRY_USER -p $REGISTRY_PASS && 
           docker ps -aq | xargs docker stop | xargs docker rm &&
           docker run -d -p 8088:8088 $IMAGE_NAME:$IMAGE_TAG"
